### ISSUE TITLE
Labels funktionieren nicht

### ISSUE THREAD

**Issue by MrMonk3y** [AndreasFMueller/Seminar17#38]
Labels von z.B. Geodäten und Schwarzschild funktionieren in unserem Kapitel nicht.

\chapter{Geodäten
\label{skript:chapter:geodaeten}}

Müsste \label nicht nach der geschwungnen Klammern stehen? Etwa so:

\chapter{Geodäten}
\label{skript:chapter:geodaeten}

**Comment by AndreasFMueller** [comment]
Sie haben Tipfehler in den Labels. Die Platzierung der Labels ist konsistent mit dem Prinzip, dass ein Label immer in dem Kontext stehen soll, auf den er verweisen soll. Die von Ihnen vorgeschlagene Platzierung ist auch möglich, aber ich bevorzuge diejenige, die im Skriptteil durchgezogen ist.
